sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t arduinominas/nanopi-m3 .
# test image
- docker run arduinominas/nanopi-m3 gcc --version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep "ENV VERSION" Dockerfile | awk 'NF>1{print $NF}')
    docker tag arduinominas/nanopi-m3 arduinominas/nanopi-m3:$TAG
    docker push arduinominas/nanopi-m3:$TAG
    docker push arduinominas/nanopi-m3
  fi